language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN="dc5a3f74-6b2b-41bd-a2c9-32d60597bdd3"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - malgin.zhenya@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always